/** Responsibility-preserving CE-R2 pipeline constitution. */
export const GENESIS_T8_CE_R2_PIPELINE_VERSION = "1.0.0" as const;

export const GENESIS_T8_CE_R2_PIPELINE_STAGES = Object.freeze([
  "SELLER_AND_OFFERING_KNOWLEDGE",
  "AI_SEMANTIC_INTERPRETATION",
  "CANONICAL_SELLER_OFFERING_GRAPH",
  "TARGET_TRUTH_QUALIFIED_GRAPH",
  "AI_CONSTRAINT_IDENTIFICATION",
  "DETERMINISTIC_UDOSIB_REASONING",
  "SURVIVING_COMMERCIAL_REALITIES",
  "DETERMINISTIC_OPPORTUNITY_ORDERING",
  "AI_GROUNDED_EXPLANATION",
] as const);
export type GenesisT8CER2PipelineStage = (typeof GENESIS_T8_CE_R2_PIPELINE_STAGES)[number];

export const GENESIS_T8_CE_R2_PIPELINE_LAWS = Object.freeze([
  "AI_SEMANTICS_MUST_PRECEDE_UDOSIB_REASONING",
  "TRUTH_QUALIFICATION_MUST_PRECEDE_UDOSIB_REASONING",
  "UDOSIB_MUST_NOT_CALL_AI_TO_DECIDE_NUMERIC_OUTPUTS",
  "AI_EXPLANATION_MUST_FOLLOW_AND_BE_GROUNDED_IN_DETERMINISTIC_OUTPUT",
  "TARGETED_RESEARCH_RETURNS_THROUGH_TI_BEFORE_RECALCULATION",
] as const);
