import { notFound } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/shell";
import { Card, PageHeader } from "@/components/ui";
import { ContactReviewActions } from "@/components/contact-review-actions";
import { requirePageUser } from "@/lib/auth/page-user";
import { getContact, contactCounts } from "@/lib/contacts/repository";
import { companyCounts } from "@/lib/discovery/repository";
import { listCampaigns } from "@/lib/campaigns/repository";
import { Building2, ExternalLink, MapPin, ShieldCheck, Target, CheckCircle2, Mail, ContactRound } from "@/components/icons";
import { formatDateTime } from "@/lib/date-time";
export const dynamic="force-dynamic";
const labels:Record<string,string>={PENDING_REVIEW:"Awaiting review",APPROVED:"Approved",REJECTED:"Not selected",HOLD:"Held",ARCHIVED:"Archived"};
const confidenceLabel=(score:number)=>score>=85?"High confidence":score>=65?"Moderate confidence":"Limited confidence";
export default async function ContactDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const user=await requirePageUser(`/contacts/${id}`);
 const [contact,contacts,companies,campaigns]=await Promise.all([getContact(id),contactCounts(),companyCounts(),listCampaigns()]);if(!contact)notFound();
 const unknowns=Array.isArray(contact.unknowns_json)?contact.unknowns_json:[];const risks=Array.isArray(contact.risk_flags_json)?contact.risk_flags_json:[];
 return <AppShell title="Contact evidence" user={user} workspaceStats={{campaigns:campaigns.length,companies:companies.total,replies:0,opportunities:0}}>
  <PageHeader eyebrow={contact.campaign_name} title={contact.full_name} subtitle={`${contact.role_title} at ${contact.company_name}. Review identity, role and contact-channel evidence before outreach.`}/>
  <Card className="company-report-hero"><div><div className="report-kicker"><ShieldCheck size={15}/> Contact identity supported by public evidence</div><h2 className="contact-detail-role">{contact.role_title}</h2><div className="contact-company detail"><Building2 size={16}/><strong>{contact.company_name}</strong>{contact.location&&<><MapPin size={15}/><span>{contact.location}</span></>}</div><p className="company-summary">{contact.reason_selected}</p>{contact.company_website_url&&<a className="button secondary" href={contact.company_website_url} target="_blank" rel="noreferrer">Open official company website <ExternalLink size={15}/></a>}</div><div className="company-score-card"><strong>{contact.overall_confidence}</strong><span>Overall confidence</span><div className="fit-track section"><span style={{width:`${contact.overall_confidence}%`}}/></div><span>{confidenceLabel(contact.overall_confidence)}</span></div></Card>

  <Card className="section contact-information-card"><div className="section-head"><div><div className="card-title">Contact information</div><div className="card-subtitle">Every channel is independently classified. Unknown information is never invented.</div></div><ContactRound size={20}/></div><div className="contact-method-grid section">
   <div className={`contact-method ${contact.email_status.toLowerCase()}`}><div className="contact-method-icon"><Mail size={18}/></div><div><span>Email</span><strong>{contact.email_address||"Unknown"}</strong><small>{contact.email_status==="VERIFIED"?"Verified on an official source":contact.email_status==="LIKELY"?"Likely company-format address":"No supportable email found"}</small></div><div className="contact-method-score"><strong>{contact.email_confidence}</strong><span>{contact.email_status.replaceAll("_"," ")}</span></div>{contact.email_source_url&&<a href={contact.email_source_url} target="_blank" rel="noreferrer" aria-label="Open email evidence"><ExternalLink size={16}/></a>}</div>
   <div className={`contact-method ${contact.linkedin_status.toLowerCase()}`}><div className="contact-method-icon"><ExternalLink size={18}/></div><div><span>LinkedIn</span><strong>{contact.linkedin_profile_url?"Matched profile":"Unknown"}</strong><small>{contact.linkedin_status==="VERIFIED"?"Identity and employer verified":contact.linkedin_status==="HIGH_CONFIDENCE"?"Strong identity and employer match":"No supportable profile found"}</small></div><div className="contact-method-score"><strong>{contact.linkedin_confidence}</strong><span>{contact.linkedin_status.replaceAll("_"," ")}</span></div>{contact.linkedin_profile_url&&<a href={contact.linkedin_profile_url} target="_blank" rel="noreferrer" aria-label="Open LinkedIn profile"><ExternalLink size={16}/></a>}</div>
  </div></Card>

  <div className="report-two-column section"><Card><div className="card-title">Confidence breakdown</div><div className="card-subtitle">Each dimension is scored independently from available evidence.</div><div className="fit-breakdown section">{[["Identity",contact.identity_confidence],["Current role",contact.role_confidence],["Buying relevance",contact.buying_relevance],["Operational relevance",contact.operational_relevance],["Evidence quality",contact.evidence_quality]].map(([l,v])=><div className="fit-row" key={String(l)}><div><span>{l}</span><strong>{v}/100</strong></div><div className="fit-track"><span style={{width:`${v}%`}}/></div></div>)}</div></Card><Card><div className="card-title">Workspace decision</div><div className="strategy-grid section"><div className="strategy-item"><Target size={18}/><div><span>Campaign</span><strong>{contact.campaign_name}</strong></div></div><div className="strategy-item"><Building2 size={18}/><div><span>Company</span><strong>{contact.company_name}</strong></div></div><div className="strategy-item"><ShieldCheck size={18}/><div><span>Current status</span><strong>{labels[contact.review_status]??contact.review_status}</strong></div></div></div><ContactReviewActions id={contact.id} campaignId={contact.campaign_id} status={contact.review_status} note={contact.review_note}/></Card></div>
  <div className="grid cols-2 section"><Card><div className="card-title">Why SalesPilot selected this person</div><div className="verified-empty section"><CheckCircle2 size={20}/><span>{contact.reason_selected}</span></div>{contact.department&&<p className="company-summary">Department: {contact.department}</p>}</Card><Card><div className="card-title">Unknowns and risk flags</div>{unknowns.length?<div className="uncertainty-box"><ShieldCheck size={18}/><div>{unknowns.map((x:string,i:number)=><p key={i}>{x}</p>)}</div></div>:<div className="verified-empty section"><CheckCircle2 size={20}/><span>No material unknowns were returned.</span></div>}{risks.length>0&&<div className="risk-flags">{risks.map((x:string,i:number)=><span key={i}>{x}</span>)}</div>}</Card></div>
  <Card className="section"><div className="section-head"><div><div className="card-title">Contact evidence</div><div className="card-subtitle">Open original sources before approval. Email and LinkedIn evidence are shown alongside identity and role evidence.</div></div><span className="badge green">{contact.evidence?.length??0} source{(contact.evidence?.length??0)===1?"":"s"}</span></div><div className="evidence-list section">{(contact.evidence??[]).map((e:any)=><div className="evidence-item" key={e.id}><div><div className="evidence-verified"><ShieldCheck size={15}/> {e.evidence_type.replaceAll("_"," ").toLowerCase()} · {e.source_kind.replaceAll("_"," ").toLowerCase()}</div><strong>{e.claim}</strong>{e.excerpt&&<p>“{e.excerpt}”</p>}<span>{e.source_title||e.source_domain||"Official public source"}</span></div><a href={e.source_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></div>)}</div></Card>
  <Card className="section"><div className="card-title">Review history</div>{(contact.review_history??[]).length?<div className="review-history section">{contact.review_history.map((r:any)=><div className="review-history-item" key={r.id}><div><strong>{labels[r.next_status]??r.next_status}</strong><span>{r.note||"No review note was added."}</span></div><time>{formatDateTime(r.occurred_at)}</time></div>)}</div>:<div className="verified-empty section"><span>This contact is awaiting its first review.</span></div>}</Card><div className="section"><Link className="button secondary" href="/contacts">← Back to contacts</Link></div>
 </AppShell>
}
