import { notFound } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/shell";
import { Card, PageHeader } from "@/components/ui";
import { CompanyReviewActions } from "@/components/company-review-actions";
import { requirePageUser } from "@/lib/auth/page-user";
import { getCompany, companyCounts } from "@/lib/discovery/repository";
import { listCampaigns } from "@/lib/campaigns/repository";
import { CheckCircle2, ExternalLink, ShieldCheck } from "@/components/icons";
export const dynamic="force-dynamic";
export default async function CompanyDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const user=await requirePageUser(`/companies/${id}`);const [company,counts,campaigns]=await Promise.all([getCompany(id),companyCounts(),listCampaigns()]);if(!company)notFound();const payload=company.payload??{};return <AppShell title={company.company_name} user={user} workspaceStats={{campaigns:campaigns.length,companies:counts.total,replies:0,opportunities:0}}><PageHeader eyebrow="Company recommendation" title={company.company_name} subtitle={`Found for ${company.campaign_name}. Review the evidence before deciding whether this company should continue.`} action={<span className="badge green">{company.match_label} · {company.confidence}/100</span>}/><div className="grid cols-2"><Card><div className="section-head"><div><div className="card-title">Company overview</div><div className="card-subtitle">Publicly supported information only</div></div><a className="button secondary" href={company.website_url} target="_blank" rel="noreferrer">Official website <ExternalLink size={15}/></a></div><p className="company-summary">{company.summary}</p><div className="company-facts"><div><span>Industry</span><strong>{company.industry||"Not confirmed"}</strong></div><div><span>Country</span><strong>{company.country||"Not confirmed"}</strong></div><div><span>Review status</span><strong>{company.review_status.replaceAll('_',' ').toLowerCase()}</strong></div><div><span>Confidence</span><strong>{company.confidence}/100</strong></div></div><CompanyReviewActions id={company.id} status={company.review_status}/></Card><Card><div className="card-title">Why SalesPilot recommended this company</div><div className="card-subtitle">Campaign fit is explained rather than assumed.</div><div className="recommendation-reasons section">{(payload.why??[]).map((reason:string,index:number)=><div key={index}><CheckCircle2 size={19}/><span>{reason}</span></div>)}</div>{(payload.uncertainties??[]).length>0&&<div className="uncertainty-box"><ShieldCheck size={18}/><div><strong>What remains uncertain</strong>{payload.uncertainties.map((item:string,index:number)=><p key={index}>{item}</p>)}</div></div>}</Card></div><Card className="section"><div className="card-title">Evidence</div><div className="card-subtitle">Open the original public sources before approving this recommendation.</div><div className="evidence-list section">{(company.evidence??[]).map((e:any)=><div className="evidence-item" key={e.id}><div><strong>{e.claim}</strong>{e.excerpt&&<p>“{e.excerpt}”</p>}<span>{e.source_title||"Public website evidence"}</span></div><a href={e.source_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></div>)}</div></Card><div className="section"><Link className="button secondary" href="/companies">← Back to companies</Link></div></AppShell>}
