"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck, Building2, MapPin, CheckCircle2 } from "@/components/icons";

type Row = { id:string; campaign_id:string; campaign_name:string; company_name:string; full_name:string; role_title:string; department?:string|null; location?:string|null; reason_selected:string; overall_confidence:number; confidence_label:string; evidence_count:number; evidence_quality:number; review_status:string };
const labels:Record<string,string>={PENDING_REVIEW:"Awaiting review",APPROVED:"Approved",REJECTED:"Not selected",HOLD:"Held",ARCHIVED:"Archived"};
function reasons(row: Row) {
  const items = [
    row.overall_confidence >= 80 ? "Strong identity and role confidence" : "Identity supported by public evidence",
    row.department ? `${row.department} relevance` : "Operational buying relevance",
    row.evidence_count > 1 ? `${row.evidence_count} supporting evidence sources` : "Official evidence available",
  ];
  return items.slice(0, 3);
}
export function ContactReviewQueue({ rows }: { rows: Row[] }) {
 const router=useRouter(); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(""); const set=useMemo(()=>new Set(selected),[selected]); const all=rows.length>0&&selected.length===rows.length;
 async function review(status:"APPROVED"|"REJECTED"|"HOLD") { if(!selected.length)return; setBusy(status); setError(""); try { const contacts=rows.filter(r=>set.has(r.id)).map(r=>({id:r.id,campaignId:r.campaign_id})); const res=await fetch("/api/contacts/review-bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contacts,status})}); if(!res.ok)throw new Error(); setSelected([]); router.refresh(); } catch { setError("SalesPilot could not save the selected contact reviews."); } finally { setBusy(null); } }
 return <><div className="review-queue-toolbar"><label className="review-select-all"><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:rows.map(r=>r.id))}/> Select all on this page</label><div><strong>{selected.length}</strong> selected</div><button className="button primary" disabled={!selected.length||!!busy} onClick={()=>review("APPROVED")}>{busy==="APPROVED"?"Approving…":"Approve selected"}</button><button className="button secondary" disabled={!selected.length||!!busy} onClick={()=>review("HOLD")}>{busy==="HOLD"?"Holding…":"Hold selected"}</button><button className="button secondary" disabled={!selected.length||!!busy} onClick={()=>review("REJECTED")}>{busy==="REJECTED"?"Saving…":"Reject selected"}</button></div>{error&&<p className="review-error">{error}</p>}
 <div className="company-card-grid">{rows.map(r=><article className={`card company-result-card reviewable contact-card ${set.has(r.id)?"selected":""}`} key={r.id}><label className="company-select"><input type="checkbox" checked={set.has(r.id)} onChange={()=>setSelected(x=>x.includes(r.id)?x.filter(i=>i!==r.id):[...x,r.id])} aria-label={`Select ${r.full_name}`}/></label><Link href={`/contacts/${r.id}`} className="company-card-link"><div className="company-result-head"><div className="company-title-block"><span className="eyebrow">{r.campaign_name}</span><h3>{r.full_name}</h3><div className="contact-role">{r.role_title}</div></div><div className="confidence-panel"><strong>{r.overall_confidence}/100</strong><span><ShieldCheck size={13}/> {r.confidence_label.toLowerCase()}</span></div></div><div className="contact-company"><Building2 size={15}/><strong>{r.company_name}</strong>{r.location&&<><span>·</span><MapPin size={14}/><span>{r.location}</span></>}</div><p className="company-summary-card">{r.reason_selected}</p><div className="contact-reason-list"><span>Recommended because</span>{reasons(r).map(item=><div key={item}><CheckCircle2 size={13}/>{item}</div>)}</div><div className="company-result-meta"><span>{r.department||"Department not confirmed"}</span><span>{r.evidence_count} evidence source{Number(r.evidence_count)===1?"":"s"}</span></div><div className="evidence-meter"><div><span>Evidence quality</span><strong>{r.evidence_quality}/100</strong></div><div className="evidence-meter-track"><span style={{width:`${r.evidence_quality}%`}}/></div></div><div className="company-result-footer"><span className={`review-status ${r.review_status.toLowerCase()}`}>{labels[r.review_status]??r.review_status}</span><span className="open-report">Open contact evidence →</span></div></Link></article>)}</div></>;
}
