// G4 Phase 1 preserved boundary: No outreach is generated or sent.
// G3.5 preserved product language: Approved opportunities, ready for the next move. No email is sent during G3.5.
import { AppShell } from "@/components/shell";
import { Card, Metric, PageHeader } from "@/components/ui";
import { EngagementReviewQueue } from "@/components/engagement-review-queue";
import { requirePageUser } from "@/lib/auth/page-user";
import { listEngagementReviewQueue } from "@/lib/engagement/review-repository";
import { CheckCircle2, MessageSquareReply, ShieldCheck, Target } from "@/components/icons";
export const dynamic="force-dynamic";
export default async function EngagementPage(){const user=await requirePageUser("/replies");const rows=await listEngagementReviewQueue();const review=rows.filter(r=>r.status==="DRAFT_REVIEW").length;const approved=rows.filter(r=>r.status==="APPROVED_TO_SEND").length;const strong=rows.filter(r=>(r.ai_engagement_score??0)>=85).length;const average=rows.length?Math.round(rows.reduce((n,r)=>n+(r.ai_engagement_score??0),0)/rows.length):0;return <AppShell title="Engagement" user={user}><PageHeader eyebrow="Engagement" title="Review the conversations SalesPilot wants to start" subtitle="Every recommended engagement is grounded in the approved opportunity, independently quality-checked, and presented with transparent commercial reasoning before it can progress." action={<span className="badge green"><ShieldCheck size={14}/> AI quality gate passed</span>}/><div className="grid cols-4"><Metric label="Awaiting review" value={String(review)} foot="Ready for your judgement" tone={review?"positive":undefined}/><Metric label="Ready to execute" value={String(approved)} foot="Send, copy, open or complete"/><Metric label="Exceptional drafts" value={String(strong)} foot="Engagement score 85+"/><Metric label="Average score" value={String(average)} foot="Across visible drafts"/></div><Card className="opportunity-review-flow section"><div><Target size={18}/><span>Opportunity understood</span></div><i>→</i><div><MessageSquareReply size={18}/><span>Engagement prepared</span></div><i>→</i><div className="active"><ShieldCheck size={18}/><span>Human review</span></div><i>→</i><div><CheckCircle2 size={18}/><span>Ready to execute</span></div></Card>{rows.length?<EngagementReviewQueue rows={rows}/>:<Card className="section"><div className="empty"><h3>No engagement is awaiting review</h3><p>SalesPilot will place evidence-backed engagements here after commercial reasoning, generation and independent quality review are complete.</p></div></Card>}</AppShell>}
