import Link from "next/link";
import { AppShell } from "@/components/shell";
import { Card, PageHeader } from "@/components/ui";
import { requirePageUser } from "@/lib/auth/page-user";
import { listCompanies, companyCounts } from "@/lib/discovery/repository";
import { listCampaigns } from "@/lib/campaigns/repository";
export const dynamic="force-dynamic";
function statusLabel(value:string){return ({PENDING_REVIEW:"Awaiting review",APPROVED:"Approved",REJECTED:"Rejected",ARCHIVED:"Archived"} as Record<string,string>)[value]??"Awaiting review"}
export default async function Companies({searchParams}:{searchParams:Promise<{status?:string}>}){const user=await requirePageUser('/companies');const {status}=await searchParams;const [rows,counts,campaigns]=await Promise.all([listCompanies(status?{status}:undefined),companyCounts(),listCampaigns()]);return <AppShell title="Companies" user={user} workspaceStats={{campaigns:campaigns.length,companies:counts.total,replies:0,opportunities:0}}><PageHeader eyebrow="Company discovery" title="Companies" subtitle="Real businesses SalesPilot found for your approved outbound sales campaigns, with evidence and confidence for every recommendation."/><div className="company-filter-row"><Link className={`filter-chip ${!status?'active':''}`} href="/companies">All · {counts.total}</Link><Link className={`filter-chip ${status==='PENDING_REVIEW'?'active':''}`} href="/companies?status=PENDING_REVIEW">Awaiting review · {counts.pending}</Link><Link className={`filter-chip ${status==='APPROVED'?'active':''}`} href="/companies?status=APPROVED">Approved · {counts.approved}</Link></div>{rows.length===0?<Card><div className="empty"><h3>{campaigns.length?"Company discovery is preparing":"No companies yet"}</h3><p>{campaigns.length?"SalesPilot will add evidence-backed recommendations here as discovery completes.":"Launch an outbound sales campaign to begin company discovery."}</p></div></Card>:<div className="company-card-grid">{rows.map(row=><Link href={`/companies/${row.id}`} className="card company-result-card" key={row.id}><div className="company-result-head"><div><span className="eyebrow">{row.campaign_name}</span><h3>{row.company_name}</h3></div><span className="badge green">{row.confidence}/100</span></div><p>{row.summary}</p><div className="company-result-meta"><span>{row.industry||"Industry not confirmed"}</span><span>{row.country||"Location not confirmed"}</span><span>{row.evidence_count} evidence source{Number(row.evidence_count)===1?'':'s'}</span></div><div className="company-result-footer"><span className={`review-status ${row.review_status.toLowerCase()}`}>{statusLabel(row.review_status)}</span><strong>{row.match_label}</strong></div></Link>)}</div>}</AppShell>}
