import "server-only";
import { randomUUID } from "node:crypto";
import { databaseRequest } from "@/lib/database/postgrest";
import { isAiGovernanceDeferred, aiParallelCapacityReason } from "@/lib/ai/governance";
import { isOpenAIBackgroundPending } from "@/lib/ai/background-response";
import { ensureGenesisG8ContractClaims, insertGenesisG8Evidence, upsertGenesisG8Entity } from "./persistence/repository";
import { getMrTi2ClaimContract } from "./truth-v2/contracts";
import { hydrateGenesisG8EntityTruth } from "./hydration";
import { researchGenesisG82CompanyDepth, type DepthEvidence } from "./autonomous-depth-openai";
import type { GenesisG8EntityType } from "./entity-types";

export const GENESIS_G82_DEPTH_WORKER_VERSION="G8.2-DEPTH-WORKER-1.0" as const;
type Job={id:string;target_id:string;company_entity_id:string;canonical_domain:string;attempt_count:number;lease_token:string};
function clean(v:unknown){return typeof v==="string"?v.trim():"";} function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)||"unknown";}
async function membership(targetId:string,entityId:string,entityType:"contact"|"route",domain:string){await databaseRequest("rpc/record_genesis_g82_expansion_membership",{method:"POST",body:JSON.stringify({p_target_id:targetId,p_entity_id:entityId,p_entity_type:entityType,p_canonical_domain:domain})});}
async function persistEvidence(entityId:string,entityType:GenesisG8EntityType,items:DepthEvidence[],ref:string){const claims=await ensureGenesisG8ContractClaims(entityId,entityType);const byKey=new Map(claims.map(c=>[c.claimKey,c]));let count=0;for(const e of items){const claim=byKey.get(e.claimKey);if(!claim)continue;try{const u=new URL(e.sourceUrl);await insertGenesisG8Evidence({claimId:claim.id,direction:e.direction==="CONTRADICT"?"CONTRADICTS":"SUPPORTS",sourceClass:e.sourceClass,sourceUri:e.sourceUrl,sourceRef:e.sourceTitle,sourceFamily:u.hostname.replace(/^www\./,""),excerpt:e.excerpt,strength:e.directness/100,traceability:e.traceability/100,independence:1,observedAt:new Date().toISOString(),channel:"DISCOVERY_INTELLIGENCE",provenance:{channel:"DISCOVERY_INTELLIGENCE",discoveredAt:new Date().toISOString(),sourceRef:ref}});count++;}catch{}}await hydrateGenesisG8EntityTruth(entityId,{persistIfChanged:true});return count;}
async function settle(job:Job,status:"QUEUED"|"COMPLETED"|"FAILED",contacts:number,routes:number,error?:string|null){await databaseRequest("rpc/settle_genesis_g82_depth_job",{method:"POST",body:JSON.stringify({p_job_id:job.id,p_lease_token:job.lease_token,p_status:status,p_contacts_persisted:contacts,p_routes_persisted:routes,p_error:error??null})});}
async function run(job:Job){let contacts=0,routes=0;try{const result=await researchGenesisG82CompanyDepth({jobId:job.id,companyEntityId:job.company_entity_id,domain:job.canonical_domain});for(const c of result.contacts){const key=`${job.canonical_domain}::contact::${slug(c.fullName)}::${slug(c.roleTitle)}`;const entity=await upsertGenesisG8Entity({entityType:"contact",canonicalKey:key,displayName:c.fullName,contractVersion:getMrTi2ClaimContract("contact").version});await persistEvidence(entity.id,"contact",c.evidence,`g82-depth:${job.id}:${job.company_entity_id}`);await membership(job.target_id,entity.id,"contact",job.canonical_domain);contacts++;}for(const r of result.routes){const channel=clean(r.channelValue)||r.channelType;const key=`${job.canonical_domain}::route::${slug(r.targetRole??r.label)}::${r.channelType.toLowerCase()}::${slug(channel)}`;const entity=await upsertGenesisG8Entity({entityType:"route",canonicalKey:key,displayName:r.label,contractVersion:getMrTi2ClaimContract("route").version});await persistEvidence(entity.id,"route",r.evidence,`g82-depth:${job.id}:${job.company_entity_id}`);await membership(job.target_id,entity.id,"route",job.canonical_domain);routes++;}await settle(job,"COMPLETED",contacts,routes);return {jobId:job.id,outcome:"COMPLETED" as const,contacts,routes};}catch(error){const message=error instanceof Error?error.message:String(error);if(isOpenAIBackgroundPending(error)||isAiGovernanceDeferred(error)||aiParallelCapacityReason(error)){await settle(job,"QUEUED",contacts,routes,message);return {jobId:job.id,outcome:"PENDING" as const,contacts,routes,error:message};}const retry=job.attempt_count<5&&!/NOT_CONFIGURED|INVALID_SCHEMA/.test(message);await settle(job,retry?"QUEUED":"FAILED",contacts,routes,message);return {jobId:job.id,outcome:retry?"FAILED_RETRYABLE" as const:"FAILED_FINAL" as const,contacts,routes,error:message};}}
export async function ensureGenesisG82DepthBacklog(limit=50){await databaseRequest("rpc/ensure_genesis_g82_depth_backlog",{method:"POST",body:JSON.stringify({p_limit:Math.max(1,Math.min(250,Math.trunc(limit)))})});}
export async function runGenesisG82DepthWorker(limit=1){const jobs=await databaseRequest<Job[]>("rpc/claim_genesis_g82_depth_jobs",{method:"POST",body:JSON.stringify({p_limit:Math.max(1,Math.min(2,Math.trunc(limit))),p_worker_id:`g82-depth:${process.env.VERCEL_REGION??"local"}:${randomUUID()}`,p_lease_seconds:180})});const receipts=[] as Awaited<ReturnType<typeof run>>[];for(const job of jobs)receipts.push(await run(job));return {workerVersion:GENESIS_G82_DEPTH_WORKER_VERSION,claimed:jobs.length,completed:receipts.filter(r=>r.outcome==="COMPLETED").length,pending:receipts.filter(r=>r.outcome==="PENDING").length,failedRetryable:receipts.filter(r=>r.outcome==="FAILED_RETRYABLE").length,failedFinal:receipts.filter(r=>r.outcome==="FAILED_FINAL").length,contactsPersisted:receipts.reduce((n,r)=>n+r.contacts,0),routesPersisted:receipts.reduce((n,r)=>n+r.routes,0),receipts};}
