import "server-only";
import { fetchResumableOpenAIResponse, isOpenAIBackgroundPending } from "@/lib/ai/background-response";
import { reserveAiRequest, completeAiRequest, responseUsage } from "@/lib/ai/governance";
import { aiRequestTimeoutMs, classifyOpenAITransportError } from "@/lib/ai/request-policy";
import { resolveOpenAIModel } from "@/lib/intelligence/model-router";
import { stableFingerprint } from "@/lib/ai/cost-optimisation";
import { decodeAiJson } from "./ai-canonicalisation";
import type { GenesisG8EvidenceSourceClass } from "./evidence-types";

export const GENESIS_G82_DEPTH_RESEARCH_VERSION="G8.2-DEPTH-1.0" as const;
export type DepthEvidence={claimKey:string;sourceClass:GenesisG8EvidenceSourceClass;sourceUrl:string;sourceTitle:string|null;excerpt:string;directness:number;authority:number;traceability:number;direction:"SUPPORT"|"CONTRADICT"};
export type DepthContact={fullName:string;roleTitle:string;email:string|null;linkedin:string|null;evidence:DepthEvidence[]};
export type DepthRoute={label:string;channelType:"DIRECT_EMAIL"|"LINKEDIN"|"DEPARTMENT_EMAIL"|"GENERAL_EMAIL"|"SWITCHBOARD"|"INTRODUCTION"|"UNKNOWN";channelValue:string|null;targetRole:string|null;contactName:string|null;evidence:DepthEvidence[]};
export type GenesisG82DepthResult={schemaVersion:"genesis-g82-depth/v1";contacts:DepthContact[];routes:DepthRoute[]};

const SOURCE_CLASSES=["REGULATORY_OR_GOVERNMENT","OFFICIAL_PRIMARY","OFFICIAL_PROFILE","MAJOR_REPUTABLE_MEDIA","INDUSTRY_PUBLICATION","COMMERCIAL_DATABASE","BUSINESS_DIRECTORY","SOCIAL_OR_COMMUNITY","SEARCH_SNIPPET","UNKNOWN"] as const;
const ev={type:"object",additionalProperties:false,required:["claimKey","sourceClass","sourceUrl","sourceTitle","excerpt","directness","authority","traceability","direction"],properties:{claimKey:{type:"string"},sourceClass:{type:"string",enum:SOURCE_CLASSES},sourceUrl:{type:"string"},sourceTitle:{type:["string","null"]},excerpt:{type:"string"},directness:{type:"integer",minimum:0,maximum:100},authority:{type:"integer",minimum:0,maximum:100},traceability:{type:"integer",minimum:0,maximum:100},direction:{type:"string",enum:["SUPPORT","CONTRADICT"]}}} as const;
const schema={type:"object",additionalProperties:false,required:["schemaVersion","contacts","routes"],properties:{schemaVersion:{type:"string",enum:["genesis-g82-depth/v1"]},contacts:{type:"array",maxItems:3,items:{type:"object",additionalProperties:false,required:["fullName","roleTitle","email","linkedin","evidence"],properties:{fullName:{type:"string"},roleTitle:{type:"string"},email:{type:["string","null"]},linkedin:{type:["string","null"]},evidence:{type:"array",maxItems:6,items:ev}}}},routes:{type:"array",maxItems:4,items:{type:"object",additionalProperties:false,required:["label","channelType","channelValue","targetRole","contactName","evidence"],properties:{label:{type:"string"},channelType:{type:"string",enum:["DIRECT_EMAIL","LINKEDIN","DEPARTMENT_EMAIL","GENERAL_EMAIL","SWITCHBOARD","INTRODUCTION","UNKNOWN"]},channelValue:{type:["string","null"]},targetRole:{type:["string","null"]},contactName:{type:["string","null"]},evidence:{type:"array",maxItems:6,items:ev}}}}}} as const;

function clamp(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):0;}
function clean(v:unknown){return typeof v==="string"?v.trim():"";}
function parseEvidence(v:any):DepthEvidence[]{return Array.isArray(v)?v.filter(x=>x&&typeof x==="object"&&clean(x.claimKey)&&clean(x.sourceUrl)&&clean(x.excerpt)).slice(0,6).map(x=>({claimKey:clean(x.claimKey),sourceClass:(SOURCE_CLASSES as readonly string[]).includes(x.sourceClass)?x.sourceClass:"UNKNOWN",sourceUrl:clean(x.sourceUrl),sourceTitle:x.sourceTitle==null?null:clean(x.sourceTitle),excerpt:clean(x.excerpt).slice(0,420),directness:clamp(x.directness),authority:clamp(x.authority),traceability:clamp(x.traceability),direction:x.direction==="CONTRADICT"?"CONTRADICT":"SUPPORT"})):[];}
function accept(raw:unknown):GenesisG82DepthResult{const r=raw as any;if(!r||r.schemaVersion!=="genesis-g82-depth/v1")throw new Error("GENESIS_G82_DEPTH_INVALID_SCHEMA");const contacts=(Array.isArray(r.contacts)?r.contacts:[]).slice(0,3).map((x:any)=>({fullName:clean(x.fullName),roleTitle:clean(x.roleTitle),email:x.email==null?null:clean(x.email),linkedin:x.linkedin==null?null:clean(x.linkedin),evidence:parseEvidence(x.evidence)})).filter((x:any)=>x.fullName&&x.roleTitle&&x.evidence.length>=2);const routes=(Array.isArray(r.routes)?r.routes:[]).slice(0,4).map((x:any)=>({label:clean(x.label),channelType:(["DIRECT_EMAIL","LINKEDIN","DEPARTMENT_EMAIL","GENERAL_EMAIL","SWITCHBOARD","INTRODUCTION","UNKNOWN"].includes(x.channelType)?x.channelType:"UNKNOWN") as DepthRoute["channelType"],channelValue:x.channelValue==null?null:clean(x.channelValue),targetRole:x.targetRole==null?null:clean(x.targetRole),contactName:x.contactName==null?null:clean(x.contactName),evidence:parseEvidence(x.evidence)})).filter((x:any)=>x.label&&x.evidence.length>=1);return {schemaVersion:"genesis-g82-depth/v1",contacts,routes};}

export async function researchGenesisG82CompanyDepth(input:{jobId:string;companyEntityId:string;domain:string}){
 const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("OPENAI_API_KEY_NOT_CONFIGURED");
 const organisationId=process.env.MARKETROUTE_G8_SYSTEM_ORGANISATION_ID?.trim()??null;const model=resolveOpenAIModel("analysis").model;const timeoutMs=aiRequestTimeoutMs("GENESIS_G82_EXPANSION");
 const scope=`genesis-g82-depth:${stableFingerprint({v:GENESIS_G82_DEPTH_RESEARCH_VERSION,companyEntityId:input.companyEntityId,domain:input.domain})}`;
 const reservation=await reserveAiRequest({organisationId,campaignId:null,jobType:"GENESIS_G82_EXPANSION",jobId:input.jobId,requestScope:scope,model,estimatedCostUsd:Math.max(0.01,Number(process.env.MARKETROUTE_G82_DEPTH_ESTIMATED_COST_USD??"0.08")||0.08)});const started=Date.now();let response:Response;
 try{response=await fetchResumableOpenAIResponse({apiKey,task:"GENESIS_G82_EXPANSION",organisationId,campaignId:null,jobType:"GENESIS_G82_EXPANSION",jobId:input.jobId,requestScope:scope,model,ledgerId:reservation.ledgerId},{method:"POST",cache:"no-store",signal:AbortSignal.timeout(timeoutMs),headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,instructions:["ROLE: Genesis public-commercial depth researcher.","MISSION: Enrich one already-known company with reusable public contact and route intelligence. Do not reassess company fit and do not invent people or channels.","CONTACTS: Return at most three currently evidenced commercially relevant people. A named person requires evidence for identity/current company relationship and role. Exact email only when publicly evidenced; otherwise null. LinkedIn only when the exact public profile is supportable.","ROUTES: Return at most four currently supportable access paths. Organisational routes such as official departmental/general inboxes, switchboards, procurement pages or introduction paths are valid without a named person.","CLAIMS: Contact evidence claimKey must be one of identity, company_relationship, current_employment, role, seniority, authority, work_location, linkedin, email, email_verification, commercial_relevance. Route evidence claimKey must be one of target_company, route_identity, entry_point, decision_maker, problem, commercial_rationale, route_path, supporting_signal, dependencies, risks.","SOURCES: Prefer official company pages, official profiles, regulatory/government sources and public filings. Preserve exact URLs and concise excerpts. Never manufacture an address, person or route.","Do not calculate Truth Index, opportunity score, fit, ranking or outreach. Return exact JSON only."].join(" "),input:JSON.stringify({companyEntityId:input.companyEntityId,domain:input.domain}),tools:[{type:"web_search_preview",search_context_size:"medium"}],reasoning:{effort:"low"},text:{format:{type:"json_schema",name:"genesis_g82_depth_v1",strict:true,schema}},max_output_tokens:4200,store:false})});}catch(error){if(isOpenAIBackgroundPending(error))throw error;const t=classifyOpenAITransportError(error,"GENESIS_G82_EXPANSION",timeoutMs);await completeAiRequest({ledgerId:reservation.ledgerId,ok:false,durationMs:Date.now()-started,errorCode:t.code,errorMessage:t.error.message}).catch(()=>undefined);throw t.error;}
 const json:unknown=await response.json().catch(()=>null);if(!response.ok){await completeAiRequest({ledgerId:reservation.ledgerId,ok:false,usage:responseUsage(json),webSearchCalls:1,durationMs:Date.now()-started,errorCode:`HTTP_${response.status}`,errorMessage:JSON.stringify((json as any)?.error??null)}).catch(()=>undefined);throw new Error(`GENESIS_G82_DEPTH_OPENAI_FAILED:${response.status}`);}await completeAiRequest({ledgerId:reservation.ledgerId,ok:true,usage:responseUsage(json),webSearchCalls:1,durationMs:Date.now()-started,responseId:typeof (json as any)?.id==="string"?(json as any).id:null});return accept(decodeAiJson(json));
}
