export type GenesisG8EvidenceDirection = "SUPPORTS" | "CONTRADICTS";
export type GenesisG8EvidenceSourceClass =
  | "REGULATORY_OR_GOVERNMENT"
  | "OFFICIAL_PRIMARY"
  | "OFFICIAL_PROFILE"
  | "MAJOR_REPUTABLE_MEDIA"
  | "INDUSTRY_PUBLICATION"
  | "COMMERCIAL_DATABASE"
  | "BUSINESS_DIRECTORY"
  | "SOCIAL_OR_COMMUNITY"
  | "SEARCH_SNIPPET"
  | "UNKNOWN";
